version: "3.7"
services:
    web:
        tty: true
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 4000:4000
            - 5000:5000
            - 5001:5001
            - 8080:8080
            - 8085:8085
            - 9000:9000
            - 9005:9005
            - 9099:9099
            - 9199:9199
            - 3000:3000
        volumes:
            - ./:/app